; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23506.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BE@DHDMOABD@Pozvan?5destruktor?4?6?$AA@	; `string'
PUBLIC	??_C@_0P@LKJFJFHG@Stack?5is?5full?$CB?$AA@	; `string'
PUBLIC	??_C@_01EEMJAFIK@?6?$AA@			; `string'
PUBLIC	??_C@_0BK@GFPDMCBK@Value?5pushed?5into?5stack?3?5?$AA@ ; `string'
PUBLIC	??_C@_0BA@LJDMLEOP@Stack?5is?5empty?$CB?$AA@	; `string'
PUBLIC	??_C@_0BJ@KLKDPNDI@Value?5poped?5from?5stack?3?5?$AA@ ; `string'
PUBLIC	??_C@_0BE@HFOBAJI@Element?5at?5top?5is?3?5?$AA@	; `string'
PUBLIC	??_C@_0BB@MKODCLNH@Stack?5is?5empty?$CB?6?$AA@	; `string'
PUBLIC	??_C@_05BIEBAFMA@?5is?3?5?$AA@			; `string'
PUBLIC	??_C@_0BD@HAEGGMLF@Element?5at?3?5INDEX?5?$AA@	; `string'
EXTRN	__imp_??6?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAAEAV01@H@Z:PROC
EXTRN	??_U@YAPEAX_K@Z:PROC				; operator new[]
EXTRN	??3@YAXPEAX_K@Z:PROC				; operator delete
EXTRN	??_V@YAXPEAX@Z:PROC				; operator delete[]
;	COMDAT ??_C@_0BD@HAEGGMLF@Element?5at?3?5INDEX?5?$AA@
CONST	SEGMENT
??_C@_0BD@HAEGGMLF@Element?5at?3?5INDEX?5?$AA@ DB 'Element at: INDEX ', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_05BIEBAFMA@?5is?3?5?$AA@
CONST	SEGMENT
??_C@_05BIEBAFMA@?5is?3?5?$AA@ DB ' is: ', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@MKODCLNH@Stack?5is?5empty?$CB?6?$AA@
CONST	SEGMENT
??_C@_0BB@MKODCLNH@Stack?5is?5empty?$CB?6?$AA@ DB 'Stack is empty!', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@HFOBAJI@Element?5at?5top?5is?3?5?$AA@
CONST	SEGMENT
??_C@_0BE@HFOBAJI@Element?5at?5top?5is?3?5?$AA@ DB 'Element at top is: ', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BJ@KLKDPNDI@Value?5poped?5from?5stack?3?5?$AA@
CONST	SEGMENT
??_C@_0BJ@KLKDPNDI@Value?5poped?5from?5stack?3?5?$AA@ DB 'Value poped fro'
	DB	'm stack: ', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@LJDMLEOP@Stack?5is?5empty?$CB?$AA@
CONST	SEGMENT
??_C@_0BA@LJDMLEOP@Stack?5is?5empty?$CB?$AA@ DB 'Stack is empty!', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@GFPDMCBK@Value?5pushed?5into?5stack?3?5?$AA@
CONST	SEGMENT
??_C@_0BK@GFPDMCBK@Value?5pushed?5into?5stack?3?5?$AA@ DB 'Value pushed i'
	DB	'nto stack: ', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_01EEMJAFIK@?6?$AA@
CONST	SEGMENT
??_C@_01EEMJAFIK@?6?$AA@ DB 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0P@LKJFJFHG@Stack?5is?5full?$CB?$AA@
CONST	SEGMENT
??_C@_0P@LKJFJFHG@Stack?5is?5full?$CB?$AA@ DB 'Stack is full!', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@DHDMOABD@Pozvan?5destruktor?4?6?$AA@
CONST	SEGMENT
??_C@_0BE@DHDMOABD@Pozvan?5destruktor?4?6?$AA@ DB 'Pozvan destruktor.', 0aH
	DB	00H						; `string'
END
