; Listing generated by Microsoft (R) Optimizing Compiler Version 19.00.23506.0 

include listing.inc

INCLUDELIB OLDNAMES

PUBLIC	??_C@_0BE@DHDMOABD@Pozvan?5destruktor?4?6?$AA@	; `string'
PUBLIC	??_C@_0P@LKJFJFHG@Stack?5is?5full?$CB?$AA@	; `string'
PUBLIC	??_C@_01EEMJAFIK@?6?$AA@			; `string'
PUBLIC	??_C@_0BK@GFPDMCBK@Value?5pushed?5into?5stack?3?5?$AA@ ; `string'
PUBLIC	??_C@_0BA@LJDMLEOP@Stack?5is?5empty?$CB?$AA@	; `string'
PUBLIC	??_C@_0BJ@KLKDPNDI@Value?5poped?5from?5stack?3?5?$AA@ ; `string'
PUBLIC	??_C@_0BE@HFOBAJI@Element?5at?5top?5is?3?5?$AA@	; `string'
PUBLIC	??_C@_0BB@MKODCLNH@Stack?5is?5empty?$CB?6?$AA@	; `string'
PUBLIC	??_C@_05BIEBAFMA@?5is?3?5?$AA@			; `string'
PUBLIC	??_C@_0BD@HAEGGMLF@Element?5at?3?5INDEX?5?$AA@	; `string'
EXTRN	__imp_?rdstate@ios_base@std@@QEBAHXZ:PROC
EXTRN	__imp_?good@ios_base@std@@QEBA_NXZ:PROC
EXTRN	__imp_?flags@ios_base@std@@QEBAHXZ:PROC
EXTRN	__imp_?width@ios_base@std@@QEBA_JXZ:PROC
EXTRN	__imp_?width@ios_base@std@@QEAA_J_J@Z:PROC
EXTRN	__imp_?fill@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBADXZ:PROC
EXTRN	__imp_?rdbuf@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBAPEAV?$basic_streambuf@DU?$char_traits@D@std@@@2@XZ:PROC
EXTRN	__imp_?setstate@?$basic_ios@DU?$char_traits@D@std@@@std@@QEAAXH_N@Z:PROC
EXTRN	__imp_?_Osfx@?$basic_ostream@DU?$char_traits@D@std@@@std@@QEAAXXZ:PROC
EXTRN	__imp_?tie@?$basic_ios@DU?$char_traits@D@std@@@std@@QEBAPEAV?$basic_ostream@DU?$char_traits@D@std@@@2@XZ:PROC
EXTRN	__imp_?sputc@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAAHD@Z:PROC
EXTRN	__imp_?sputn@?$basic_streambuf@DU?$char_traits@D@std@@@std@@QEAA_JPEBD_J@Z:PROC
EXTRN	__imp___std_terminate:PROC
EXTRN	??_U@YAPEAX_K@Z:PROC				; operator new[]
EXTRN	??3@YAXPEAX_K@Z:PROC				; operator delete
EXTRN	__imp_?uncaught_exception@std@@YA_NXZ:PROC
EXTRN	??_V@YAXPEAX@Z:PROC				; operator delete[]
;	COMDAT ??_C@_0BD@HAEGGMLF@Element?5at?3?5INDEX?5?$AA@
CONST	SEGMENT
??_C@_0BD@HAEGGMLF@Element?5at?3?5INDEX?5?$AA@ DB 'Element at: INDEX ', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_05BIEBAFMA@?5is?3?5?$AA@
CONST	SEGMENT
??_C@_05BIEBAFMA@?5is?3?5?$AA@ DB ' is: ', 00H		; `string'
CONST	ENDS
;	COMDAT ??_C@_0BB@MKODCLNH@Stack?5is?5empty?$CB?6?$AA@
CONST	SEGMENT
??_C@_0BB@MKODCLNH@Stack?5is?5empty?$CB?6?$AA@ DB 'Stack is empty!', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@HFOBAJI@Element?5at?5top?5is?3?5?$AA@
CONST	SEGMENT
??_C@_0BE@HFOBAJI@Element?5at?5top?5is?3?5?$AA@ DB 'Element at top is: ', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BJ@KLKDPNDI@Value?5poped?5from?5stack?3?5?$AA@
CONST	SEGMENT
??_C@_0BJ@KLKDPNDI@Value?5poped?5from?5stack?3?5?$AA@ DB 'Value poped fro'
	DB	'm stack: ', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_0BA@LJDMLEOP@Stack?5is?5empty?$CB?$AA@
CONST	SEGMENT
??_C@_0BA@LJDMLEOP@Stack?5is?5empty?$CB?$AA@ DB 'Stack is empty!', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BK@GFPDMCBK@Value?5pushed?5into?5stack?3?5?$AA@
CONST	SEGMENT
??_C@_0BK@GFPDMCBK@Value?5pushed?5into?5stack?3?5?$AA@ DB 'Value pushed i'
	DB	'nto stack: ', 00H				; `string'
CONST	ENDS
;	COMDAT ??_C@_01EEMJAFIK@?6?$AA@
CONST	SEGMENT
??_C@_01EEMJAFIK@?6?$AA@ DB 0aH, 00H			; `string'
CONST	ENDS
;	COMDAT ??_C@_0P@LKJFJFHG@Stack?5is?5full?$CB?$AA@
CONST	SEGMENT
??_C@_0P@LKJFJFHG@Stack?5is?5full?$CB?$AA@ DB 'Stack is full!', 00H ; `string'
CONST	ENDS
;	COMDAT ??_C@_0BE@DHDMOABD@Pozvan?5destruktor?4?6?$AA@
CONST	SEGMENT
??_C@_0BE@DHDMOABD@Pozvan?5destruktor?4?6?$AA@ DB 'Pozvan destruktor.', 0aH
	DB	00H						; `string'
CONST	ENDS
END
